version: '3.8'

services:
  backend:
    build:
      context: ./backend
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongodb:27017/umrahhajj
      - JWT_SECRET=your_jwt_secret_key
      - PORT=5000
      - CORS_ORIGIN=http://localhost
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
    networks:
      - umrah-network

  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:5000/api
      - REACT_APP_GA_TRACKING_ID=UA-XXXXXXXXX-X
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - umrah-network

  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'
    networks:
      - umrah-network

volumes:
  mongo-data:

networks:
  umrah-network:
    driver: bridge
